name: iOS Build & Unit Tests

on:
  push:
    branches:
      - SPAR_iOS_App
  pull_request:

jobs:
  ios-tests:
    runs-on: macos-14

    defaults:
      run:
        working-directory: SPAR

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.0.app

      - name: Install Swift Packages
        run: xcodebuild -resolvePackageDependencies

      - name: Run Unit Tests Only (faster)
        run: |
          xcodebuild test -project SPAR.xcodeproj \
            -scheme SPAR \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -only-testing:SPARTests
