name: iOS UI Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ios-tests:
    runs-on: macos-14

    defaults:
      run:
        working-directory: SPAR

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.0.app

      - name: Install Swift Packages
        run: xcodebuild -resolvePackageDependencies

      - name: Run UI Tests
        run: |
          mkdir -p TestResults
          xcodebuild test -project SPAR.xcodeproj \
            -scheme SPAR \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -resultBundlePath TestResults/SPARTestResults.xcresult

      - name: Upload Test Results
        if: always() # run even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: SPAR-xcresult
          path: SPAR/TestResults/SPARTestResults.xcresult
