name: iOS CI for SPAR

on:
  push:
    branches: [ /SPAR_iOS_App ]
  pull_request:
    branches: [ /SPAR_iOS_App ]

jobs:
  build-and-test:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.3.app

      - name: Clean Derived Data & Simulators
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          xcrun simctl shutdown all || true
          xcrun simctl erase all || true

      - name: Run Tests with xcodebuild
        env:
          NSUnbufferedIO: YES
        run: |
          xcodebuild \
            -project SPAR/SPAR.xcodeproj \
            -scheme SPAR \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
            -derivedDataPath DerivedData \
            -enableCodeCoverage YES \
            clean test \
            | xcpretty --report html --report junit

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: SPARTestResults
          path: |
            DerivedData/Logs/Test/*.xcresult
            test_output/
